name: Release

on:
  push:
    tags:
      - "v*.*.*"   # only versioned tags

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required to see full history + tags

      - name: Fetch main
        run: git fetch origin main

      # Ensure tag commit is the tip of main
      - name: Verify tag is on main
        run: |
          TAG="${GITHUB_REF##*/}"
          COMMIT=$(git rev-list -n 1 "$TAG")
          MAIN_HEAD=$(git rev-parse origin/main)

          if [ "$COMMIT" != "$MAIN_HEAD" ]; then
            echo "❌ Tag $TAG does not point to the latest commit on main."
            exit 1
          fi
          echo "✅ Tag $TAG is exactly on main HEAD."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
