name: Smoke Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make smoke-test executable
        run: chmod +x ./pipeline-generator/tests/smoke_test.sh

      - name: Run smoke test
        run: ./pipeline-generator/tests/smoke_test.sh
